import re
import os

files_to_translate = ['api/app.py', 'api/presenz_mvp.py', 'frontend/index.html', 'frontend/app.html']

mapping = {
    # Comments & General
    "数据库、用户、订阅与媒体管理版 API": "Database, Users, Subscriptions, and Media API",
    "念念 - AI思念亲人平台": "Presenz - AI Memorial Companion",
    "配置": "Configuration",
    "数据模型": "Data Models",
    "辅助函数": "Helper Functions",
    "数据库": "Database",
    "套餐定义": "Plan Definitions",
    
    # PLAN CATALOG
    "体验版": "Trial Plan",
    "先建立第一位亲人的档案，体验基础文字陪伴与素材整理。": "Create your first profile and experience basic text chat and memory organization.",
    "思念种子": "Memory Seed",
    "保留文字与声音，让对话先变得像 ta。": "Preserve text and voice so the chat feels more like them.",
    "思念之树": "Memory Tree",
    "扩展到多位亲人和更深的语音陪伴能力。": "Expand to multiple profiles and deeper voice companion capabilities.",
    "思念花园": "Memory Garden",
    "打开语音与视频陪伴，让分身更有在场感。": "Unlock voice and video presence to make the companion feel more present.",
    "思念家族": "Memory Family",
    "面向长期家族纪念的完整权限与更高容量。": "Full permissions and higher capacity for long-term family memorials.",

    # Error Messages & Prompts
    "需要管理员权限": "Admin privileges required",
    "密码错误": "Incorrect password",
    "未找到": "Not found",
    "参数错误": "Invalid parameters",
    "账号或密码错误": "Incorrect email or password",
    "请用适合纪念陪伴场景的口吻读出这段话。": "Please read this in a tone suitable for a memorial companion.",
    "温柔": "Gentle",
    "克制": "Restrained",
    "慢一点": "Slowly",
    "深情": "Affectionate",
    "安慰": "Comforting",
    "温暖": "Warm",
    "轻一点笑意": "A slight smile",
    "MIMO 生成的陪伴语音回复": "Companion voice reply generated by AI",
    
    "你正在帮助建立一个纪念亲人的数字分身，请只提炼有助于还原这个人的真实在场感与表达气质的要点。": "You are helping build a digital memorial profile. Extract only the key points that help reconstruct their true presence and tone.",
    "只返回 JSON，不要解释，字段固定为：": "Return JSON only, no explanation. Fixed fields:",
    "当前套餐不包含语音建模上传，请先升级套餐。": "Current plan does not support voice cloning upload. Please upgrade.",
    "套餐不存在": "Plan does not exist",
    "未命名亲人": "Unnamed Loved One",
    "陪伴回复": "Companion Reply",
    
    # Let's add a function to use Gemini to translate strings not in mapping
}

import urllib.request
import urllib.parse
import json
import time

def translate_with_gemini(text):
    if text in mapping:
        return mapping[text]
    
    # Avoid translating python code parts that accidentally matched, 
    # but the regex will only match Chinese.
    
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("No API key, skipping", text[:20])
        return text
        
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
    payload = {
        "contents": [{"parts": [{"text": f"Translate this Chinese text to English. Return ONLY the English translation, no explanation, no quotes:\n\n{text}"}]}],
        "generationConfig": {"temperature": 0.1, "maxOutputTokens": 2048}
    }
    
    req = urllib.request.Request(url, data=json.dumps(payload).encode('utf-8'), headers={'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode())
            translation = res_data['candidates'][0]['content']['parts'][0]['text'].strip()
            # print(f"Translated: {text[:20]} -> {translation[:20]}")
            return translation
    except Exception as e:
        print("Error translating:", e)
        return text

with open(".env", "r") as f:
    for line in f:
        if line.startswith("GEMINI_API_KEY="):
            os.environ["GEMINI_API_KEY"] = line.strip().split("=")[1]
            break

def process_file(filepath):
    if not os.path.exists(filepath):
        return
    print(f"Processing {filepath}")
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Find all contiguous Chinese strings (including punctuation like ，。！？、)
    # We will use a regex that matches Chinese characters and common Chinese punctuation
    # \u4e00-\u9fa5 is Han characters. \u3000-\u303f are CJK symbols. \uff01-\uff5e are fullwidth forms.
    pattern = re.compile(r"[\u4e00-\u9fa5\u3000-\u303f\uff01-\uff5e]+")
    
    unique_strings = set(pattern.findall(content))
    # print(f"Found {len(unique_strings)} unique Chinese strings in {filepath}")
    
    translation_cache = {}
    for s in unique_strings:
        # Some strings might just be punctuation, skip if no Han character
        if not re.search(r"[\u4e00-\u9fa5]", s):
            continue
            
        translated = translate_with_gemini(s)
        translation_cache[s] = translated
        time.sleep(0.5) # rate limit
        
    # Replace in content (longest strings first to avoid partial replacements)
    sorted_strings = sorted(translation_cache.keys(), key=len, reverse=True)
    for s in sorted_strings:
        content = content.replace(s, translation_cache[s])
        
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Done {filepath}")

for f in files_to_translate:
    process_file(f)
